if: type = pull_request
branches:
  only:
  - master
  
language: java
sudo: required

services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

script:
  - cp build/environment/environment.properties.example build/environment/environment.properties
  - cp build/environment/testEnvironment.json.example build/environment/testEnvironment.json
  - docker-compose -f docker-compose.unittest.yml up -d --build
  - docker ps
  - docker exec runner-chrome mvn checkstyle:check
  - mvn checkstyle:check
  - docker exec runner-chrome mvn compile test "-Dcucumber.options=--tags @applydbmigrations"
  - docker exec runner-chrome mvn compile test "-Dcucumber.options=--tags @UnitTest"
  - docker exec runner-chrome mvn io.qameta.allure:allure-maven:report
  - docker-compose -f docker-compose.unittest.yml down
