language: java
sudo: required

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.m2"


script:
  - docker-compose -f docker-compose.unittest.yml up -d --build
  - mvn test "-Dcucumber.options=--tags @UnitTest" -f pom.xml
  - mvn checkstyle:check
  - mvn io.qameta.allure:allure-maven:report
  - docker-compose -f docker-compose.unittest.yml down