# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Dtective
description:        Powerful automation made easy.
lang:               en

# Site subpath, e.g. /blog
baseurl:            "/Dtective"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://catena-media.github.io/"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:

navbar:
    sticky:         true
    search:         true

# Default author settings


# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    dwane:
      name:         Dwane Debono
      title:        Maintainer
      avatar:       avatar-dwane.png
    sofia:
      name:         Sofia Vistas
      title:        Maintainer
      avatar:       avatar-sofia.png
    matyas:
      name:         Matyas Banszki
      title:        Maintainer
      avatar:       avatar-matyas.png
    ilenia:
      name:         Ilenia Castellana
      title:        Maintainer
      avatar:       avatar-ilenia.png
    andrea:
      name:         Andrea Borg
      title:        Maintainer
      avatar:       avatar-andrea.png
    evgenia:
      name:         Evgenia Chatzi
      title:        Maintainer
      avatar:       avatar-evgenia.png
    sinan:
      name:         Sinan Verdi
      title:        Maintainer
      avatar:       avatar-sinan.png

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/catenamedia/
    flickr:
    dribbble:
    github:         https://github.com/Catena-Media
    googleplus:
    instagram:      https://www.instagram.com/catenamedia
    linkedin:
    pinterest:
    twitter:
    vimeo:
    youtube:

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            false # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      We're a bunch of human maintainers at <a href="https://www.catenamedia.com/">Catena Media</a>.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
