version: '3'

# Users Guilde
## docker-compose up -d --build
## docker exec qarunner mvn test -Dtest=TestSuiteUnitTest
## docker exec qarunner mvn site site:run

services:
  QA-Automation_Runner-Chrome:
    image: qaautomationrunner
    container_name: runner-chrome
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BrowserType=${BrowserType:-chrome}
      - SeleniumHubUrl=${SeleniumHubUrl:-http://chrome-hub:4444/wd/hub}
      - IsRemoteInstance=${IsRemoteInstance:-true}
      - IsSingleInstance=${IsSingleInstance:-true}
      - WebAppUrl=${WebAppUrl:-http://examplesite}
      - WebDriverTimeout=${WebDriverTimeout:-3}
      - WebDriverDelayMS=${WebDriverDelayMS:-100}
      - WebAppUser=${WebAppUser:-admin@test.com}
      - WebAppPass=${WebAppPass:-thisisnotapassword}
      - BrowserWidth=${BrowserWidth:-1920}
      - BrowserHeight=${BrowserHeight:-1080}
      - RecordScreenshots=${RecordScreenshots:-true}
      - TestEnvironment=${TestEnvironment:-env-docker-local}
      - ChromeHeadlessMode=${ChromeHeadlessMode:-true}
      - FirefoxHeadlessMode=${FirefoxHeadlessMode:-true}
      - HighlightElements=${HighlightElements:-true}
    entrypoint: /bin/bash
    stdin_open: true
    links:
      - chrome-hub:chrome-hub
      - testwebsite:examplesite
    volumes:
      - /Users/$USER/.m2:/root/.m2
      - ./src:/tmp/qarunner/src
    network_mode: bridge
    ports:
      - 9000:9000


  chrome-hub:
    image: selenium/standalone-chrome:3.14.0-europium
    container_name: chrome-hub
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - 4444:4444
    network_mode: bridge
    links:
      - testwebsite:examplesite

  testwebsite:
    image: catenaqa/examplesite
    container_name: catenaqa-examplesite
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - postgres
    ports:
      - 8088:80
    network_mode: bridge

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lantern
    network_mode: bridge