# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-hafnium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    network_mode: bridge

  chrome:
    image: selenium/node-chrome:3.141.59-hafnium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    external_links:
      - catenaqa-examplesite:examplesite
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    network_mode: bridge

  firefox:
    image: selenium/node-firefox:3.141.59-hafnium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    external_links:
      - catenaqa-examplesite:examplesite
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    network_mode: bridge

