version: '3'

# Users Guilde
## docker-compose up -d --build
## docker exec qarunner mvn test -Dtest=TestSuiteUnitTest
## docker exec qarunner mvn site site:run

services:
  dtective:
    image: dtective-core
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BrowserType=${BrowserType:-chrome}
      - SeleniumHubUrl=${SeleniumHubUrl:-http://selenium-hub:4444/wd/hub}
      - IsRemoteInstance=${IsRemoteInstance:-true}
      - IsSingleInstance=${IsSingleInstance:-true}
      - WebAppUrl=${WebAppUrl:-http://qa-server.catena.media}
      - WebDriverTimeout=${WebDriverTimeout:-3}
      - WebDriverDelayMS=${WebDriverDelayMS:-0}
      - WebAppUser=${WebAppUser:-admin@test.com}
      - WebAppPass=${WebAppPass:-thisisnotapassword}
      - BrowserWidth=${BrowserWidth:-1920}
      - BrowserHeight=${BrowserHeight:-1080}
      - RecordScreenshots=${RecordScreenshots:-false}
      - TestEnvironment=${TestEnvironment:-env-CI}
      - ChromeHeadlessMode=${ChromeHeadlessMode:-true}
      - FirefoxHeadlessMode=${FirefoxHeadlessMode:-true}
      - HighlightElements=${HighlightElements:-false}
    entrypoint: /bin/bash
    stdin_open: true
    links:
      -  chrome-hub:selenium-hub
    volumes:
      - /Users/$USER/.m2:/root/.m2
      - ./src:/tmp/qarunner/src
    network_mode: bridge

  chrome-hub:
    image: selenium/standalone-chrome:3.14.0-europium
    container_name: chrome-hub
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - 4444:4444
    network_mode: bridge
    links:
      - testwebsite:examplesite

  examplesite:
    image: catenaqa/examplesite
    container_name: examplesite
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - postgres
    ports:
      - 8088:80
    network_mode: bridge

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lantern
    network_mode: bridge
